app/models/post.py
from app.extensions import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80))
    content = db.Column(db.Text)

    def __init__(self, title, content):
        self.title = title
        self.content = content

app/models/question.py
from app.extensions import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    answer = db.Column(db.Text)
    def __init__(self, content, answer):
        self.content = content
        self.answer = answer

app/models/result.py
from app.extensions import db


class Result(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    Real_result = db.Column(db.Float)
    PL_regression = db.Column(db.Float)
    Gradient_boosting = db.Column(db.Float)
    RNN = db.Column(db.Float)

    def __init__(self, Real_result, PL_regression, Gradient_boosting, RNN):
        self.Real_result = Real_result
        self.PL_regression = PL_regression
        self.Gradient_boosting = Gradient_boosting
        self.RNN = RNN

app/__init__.py
from flask import Flask
from config import Config
from app.extensions import db

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.posts import bp as post_bp
    app.register_blueprint(post_bp, url_prefix='/posts')

    from app.page import bp as page_bp
    app.register_blueprint(page_bp, url_prefix='/page')

    from app.questions import bp as questions_bp
    app.register_blueprint(questions_bp, url_prefix='/questions')
    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/')
def index():
    return render_template("index.html")

app/page/__init__.py
from flask import Blueprint

bp = Blueprint('page', __name__)

from app.page import routes

app/page/routes.py
from flask import render_template, request
from app.page import bp
from app.page.Build_Model_Regression import preprocessing, training_rgr, read_data
import pickle
from tensorflow.keras.models import load_model
import pandas as pd
from app.page.db_process import db_process
from app.models.result import Result


@bp.route('/', methods=['GET', 'POST'])
def index():
    return render_template("page/index.html")


@bp.route('/training', methods=['GET', 'POST'])
def training():
    if request.method == "POST":
        metrics = training_rgr()
        sms_rgr = "Training model regression complete!!!"
        sms_bst = "Training model gradient regression complete!!!"
        sms_rnn = "Training model recurrent neural network complete!!!"
        text_out = [sms_rgr, sms_bst, sms_rnn]
        return render_template("page/index.html", text_out=text_out, metrics=metrics)
    return render_template("page/index.html")


@bp.route('/testing', methods=['GET', 'POST'])
def testing():
    if request.method == "POST":
        x_test, y_test = read_data('static/Data_testing.csv')
        poly_features = preprocessing(x_test)

        model_rgr = pickle.load(open("static/polymodel.pkl", "rb"))
        y_pred_rgr = model_rgr.predict(poly_features)  # the result of the prediction by using regression

        model_bst = pickle.load(open("static/gb_model.pkl", "rb"))
        y_pred_bst = model_bst.predict(poly_features)

        model_rnn = load_model("static/rnn_model.h5")
        y_pred_rnn = model_rnn.predict(x_test).flatten()

        # save data to sql
        db_process(y_test, y_pred_rgr, y_pred_bst, y_pred_rnn)
        # message save data successfully
        mss = "# Save data successfully"
        return render_template("page/index.html", mss=mss)
    return render_template("page/index.html")


@bp.route('/result', methods=['GET', 'POST'])
def result():
    if request.method == "POST":
        results = Result.query.all() # the query all data in the table
        return render_template("page/index.html", results=results)
    return render_template("page/index.html")

app/posts/__init__.py
import random

from flask import Blueprint

from app.models.post import Post

bp = Blueprint('posts', __name__)

from app.posts import routes

app/posts/routes.py
from flask import render_template
from app.posts import bp
from app.models.post import Post

@bp.route('/')
def index():
    posts = Post.query.all()
    return render_template("posts/index.html", posts=posts)

app/questions/__init__.py
from flask import Blueprint

bp = Blueprint('questions', __name__)

from app.questions import routes

app/questions/routes.py
from flask import render_template, request, redirect, url_for
from app.questions import bp
from app.models.question import Question
from app.extensions import db


@bp.route('/', methods=['GET', 'POST'])
def index():
    questions = Question.query.all()
    if request.method == 'POST':
        new_question = Question(content=request.form['content'],
                                answer=request.form['answer'], )
        db.session.add(new_question)
        db.session.commit()
        return redirect(url_for('questions.index'))
    return render_template("questions/index.html", questions=questions)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My blog{% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('main.index')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('posts.index')}}">Post</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Others
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{url_for('page.index')}}">Statical page</a></li>
                        <li><a class="dropdown-item" href="{{url_for('questions.index')}}">Questions</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
</div>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <span class="title"><h1>{% block title %}Home page{% endblock %}</h1></span>
{% endblock %}

app/templates/page/bonus code.html
<!-- Tao form nhap dac trung dau vao cho bai toan neu muon-- !>
<div class="container shadow p-3 mb-5 bg-body rounded">
        <form action="{{ url_for('page.index') }}" method="post">
            <div class="input-group mb-3 input-group-sm">
                <span class="input-group-text">Feature 1</span>
                <input type="text" class="form-control" placeholder="House age" aria-label="Server" name="f2"
                       required="required">
                <span class="input-group-text">Feature 2</span>
                <input type="text" class="form-control" placeholder="Distance to the nearest MRT station"
                       aria-label="Server" name="f3" required="required">
            </div>
            <div class="input-group mb-3 input-group-sm">
                <span class="input-group-text">Feature 3</span>
                <input type="text" class="form-control" placeholder="Number of convenience stores"
                       aria-label="Username" name="f4" required="required">
                <span class="input-group-text">Feature 4</span>
                <input type="text" class="form-control" placeholder="Latitude" aria-label="Server" name="f5"
                       required="required">
                <span class="input-group-text">Feature 5</span>
                <input type="text" class="form-control" placeholder="Longitude"
                       aria-label="Server" name="f6" required="required">
            </div>
            {% if output %}
                <h5>Prediction using the method Polynomial Regression: {{ output[0] }}</h5>
                <h5>Prediction using the method Gradient Boosting: {{ output[1] }}</h5>
                <h5>Prediction using the method Recurrent neural network: {{ output[2] }}</h5>
            {% endif %}
            <button type="submit" class="btn btn-primary">Prediction</button>
        </form>
    </div>

app/templates/page/index.html
{% extends "base.html" %}
{% block content %}
    <br><br>
    <div>
    <span>Chúng tôi đi giải quyết bài toán dự báo giá nhà bằng 03 phương pháp:...
        Dữ liệu chúng tôi lấy từ trang kaggle.com (https://www.kaggle.com/code/aminizahra/polynomial-regression).
        Giao diện của chúng tôi chia là 03 phần:
        Phần 01: Dùng để huấn luyện các mô hình theo các bước sau:
        - step 01: load dữ liệu từ file .csv trong thư mục static.
        - step 02: Huấn luyện các mô hình với dữ liệu trên tương ứng với các thuật toán trên.
        - step 03: Sau khi huấn luyện chúng tôi lưu các mô hình vào 03 file tương ứng với 03 thuật toán: polymodel.pkl (polynomial regression),
        gb_model.pkl (gradient Boosting), rnn_model.h5 (recurrent neural network).
        Phần 02: ...
    </span>
    </div>
    <div class="container shadow p-3 mb-5 bg-body rounded">
        <form action="{{ url_for('page.training') }}" method="post">
            <ol>
                <li>Method Polynomial Regression</li>
                {% if text_out %}
                    <span style="color: blue">{{ text_out[0] }}</span><br>
                    <span style="color: blue">Mean_absolute_error:{{ metrics[0][0] }}</span><br>
                    <span style="color: blue">mean_squared_error:{{ metrics[0][1] }}</span>
                {% endif %}
                <li>Method Gradient Boosting</li>
                {% if text_out %}
                    <span style="color: blue">{{ text_out[1] }}</span><br>
                    <span style="color: blue">Mean_absolute_error:{{ metrics[1][0] }}</span><br>
                    <span style="color: blue">mean_squared_error:{{ metrics[1][1] }}</span>
                {% endif %}
                <li>Recurent Neural Network</li>
                {% if text_out %}
                    <span style="color: blue">{{ text_out[2] }}</span><br>
                    <span style="color: blue">Mean_absolute_error:{{ metrics[2][0] }}</span><br>
                    <span style="color: blue">mean_squared_error:{{ metrics[2][1] }}</span>
                {% endif %}
            </ol>
            <button type="submit" class="btn btn-primary">Build model (Training)</button>
        </form>
    </div>
    <div class="container shadow p-3 mb-5 bg-body rounded">
        <span>Please if you want to test data, click the button bellow!</span>
        <form action="{{ url_for('page.testing') }}" method="post">
            {% if mss %}
                <h5>{{ mss }}</h5>
            {% endif %}
            <button type="submit" class="btn btn-primary" name="testing">Testing the model</button>
        </form>
    </div>

    <div class="container shadow p-3 mb-5 bg-body rounded">
        <form action="{{ url_for('page.result') }}" method="post">
            <button type="submit" class="btn btn-primary">Show the result of the prediction</button>
            {% if results %}
                <div class="overflow-auto">
                    <table class="table table-sm">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Real price</th>
                            <th scope="col">Price_regression</th>
                            <th scope="col">Price_Gradient Boosting</th>
                            <th scope="col">Price_RNN</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for r in results %}
                            <tr>
                                <td>{{ r.id }}</td>
                                <td>{{ r.Real_result }}</td>
                                <td>{{ r.PL_regression }}</td>
                                <td>{{ r.Gradient_boosting }}</td>
                                <td>{{ r.RNN }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </form>
    </div>

{% endblock %}

app/templates/posts/index.html
{% extends "base.html" %}
{% block content %}
    <span class="title"><h1>{% block title %}Posts{% endblock %}</h1></span>
    <hr>
    {% for p in posts %}
        <h3>{{ p.title }}</h3>
        <h6>{{ p.content }}</h6>
        <hr>
    {% endfor %}
{% endblock %}

app/templates/questions/index.html
{% extends "base.html" %}
{% block content %}
    <span class="title"><h1>{% block title %}Question page{% endblock %}</h1></span>
    <form action="#" method="post">
        <div class="mb-3">
            <label for="#" class="form-label">Questions</label>
            <textarea class="form-control" id="textAreaExample1" rows="4" cols="10" name="content"></textarea>
        </div>
        <div class="mb-3">
            <label for="#" class="form-label">Answer</label>
            <textarea class="form-control" id="textAreaExample1" rows="4" cols="10" name="answer"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <hr>
    {% for q in questions %}
        <h4>{{ q.content}}</h4>
        <h4>{{ q.answer }}</h4>
        <hr>
    {% endfor %}
{% endblock %}